
[[window_state_room]]
stname = "window_state_room"
suffix = "home_id"
# sample 40% of the tag set, default is to sample 50%
tags = [
    # common tags
    { name = "room_id",             type = "binary(30)" },
    { name = "home_id",             type = "binary(30)" },
    { name = "sensor_id",           type = "binary(30)" },
    { name = "window_id",           type = "binary(30)" },
]
fields = [
#    { name = "ts",                  type = "timestamp" },
    { name = "state",               type = "float" },
    { name = "battery_voltage",     type = "float" },
]

[[radiator_valve_room]]
stname = "radiator_valve_room"
suffix = "home_id"
# sample 40% of the tag set, default is to sample 50%
tags = [
    # common tags
    { name = "room_id",             type = "binary(30)" },
    { name = "home_id",             type = "binary(30)" },
    { name = "radiator",            type = "binary(30)" },
    { name = "sensor_id",           type = "binary(30)" },
    # specific tags
]
fields = [
#    { name = "ts",                  type = "timestamp" },
    { name = "opening_level",       type = "float" },
    { name = "battery_voltage",     type = "float" }
]

[[air_condition_room]]
stname = "air_condition_room"
suffix = "home_id"
# sample 40% of the tag set, default is to sample 50%

tags = [
    # common tags
    { name = "room_id",             type = "binary(30)" },
    { name = "home_id",             type = "binary(30)" },
    { name = "sensor_id",           type = "binary(30)" },
    # specific tags
]
fields = [
#    { name = "ts",                  type = "timestamp" },
    { name = "temperature",         type = "float" },
    { name = "humidity",            type = "float" },
    { name = "battery_voltage",     type = "float" },
]

[[air_quality_room]]
stname = "air_quality_room"
suffix = "home_id"
# sample 40% of the tag set, default is to sample 50%

tags = [
    # common tags
    { name = "room_id",             type = "binary(30)" },
    { name = "home_id",             type = "binary(30)" },
    { name = "sensor_id",           type = "binary(30)" },
    # specific tags
]
fields = [
#    { name = "ts",                  type = "timestamp" },
    { name = "co2_level",           type = "float" },
    { name = "co_level",            type = "float" },
    { name = "battery_voltage",     type = "float" },
]

[[light_level_room]]
stname = "light_level_room"
suffix = "home_id"
# sample 40% of the tag set, default is to sample 50%
tags = [
    # common tags
    { name = "room_id",             type = "binary(30)" },
    { name = "home_id",             type = "binary(30)" },
    { name = "sensor_id",           type = "binary(30)" },
    # specific tags
]
fields = [
#    { name = "ts",                  type = "timestamp" },
    { name = "level",               type = "float" },
    { name = "battery_voltage",     type = "float" },
]

[[air_condition_outdoor]]
stname = "air_condition_outdoor"
suffix = "home_id"
# sample 40% of the tag set, default is to sample 50%
onlyselectedtf = false
tags = [
    # common tags
    { name = "home_id",             type = "binary(30)" },
    { name = "sensor_id",           type = "binary(30)" },
    # specific tags
]
fields = [
#    { name = "ts",                  type = "timestamp" },
    { name = "temperature",         type = "float" },
    { name = "humidity",            type = "float" },
    { name = "battery_voltage",     type = "float" },
]

